package Control;

public enum GameState {
	INICIANDO_PARTIDA,
	JG_ESCOLHER_CARTA_MAO,
	JG_ESCOLHER_CARTA_CAMPO1,
	AO_ESCOLHER_CARTA_CAMPO1,
	AO_ESCOLHER_CARTA_CAMPO2,
	ENCERRAR_TURNO,
	RECEBER_JOGADA;

}
