package Control;

public enum GameState {
	STARTING_MATCH,
	SELECT_HAND_CHOOSING_CARD_ON_HAND,
	SELECT_HAND_CHOOSING_CARD_ON_1,
	ATACK_CHOOSING_CARD_ON_1,
	ATACK_CHOOSING_CARD_ON_2,
	RECEIVE_MOVE;

}
